### ISSUE TITLE
Doesn't work. Incorrect bucket name generated?

### ISSUE THREAD

**Issue by boosh** [mirakl/terraform-google-gcr-cleaner#17]
I'm trying to run 0.6.0 with the following:
```
module "gcr_cleaner" {
  source  = "mirakl/gcr-cleaner/google"
  version = "0.6.0"

  cloud_scheduler_job_max_backoff_duration = 600
  cloud_run_service_location               = var.location
  cloud_run_service_maximum_instances      = 1
  gcr_repositories = [
    {
      clean_all      = true
      project_id     = data.google_project.project.id
      storage_region = "eu"
    }
  ]
}
```

The plan wants to create:
```
  + resource "google_storage_bucket_access_control" "this" {
      + bucket = "eu.artifacts.projects/<project>.appspot.com"
```

and fails. I wonder if it's because my actual bucket is `eu.artifacts.<project>.appspot.com`

Am I calling the module wrong, or is it broken? 0.5.0 also fails.

**Comment by anouarchattouna** [comment]
Hello @boosh, are you cleaning repositories for the provider's project? If so, there is no need to provide the param `project_id`. Otherwise make sure to provide the correct form of your project id.
Please have a look at [this](https://github.com/mirakl/terraform-google-gcr-cleaner/blob/main/locals.tf#L3).

**Comment by boosh** [comment]
Thanks, that's fixed it
